/*SELECT AC.ID_ASIGNACION_CABECERA, AD.ID_ASIGNACION_DETALLE, AC.ID_ESTADO FROM ASIGNACION_DETALLE AS AD
INNER JOIN ASIGNACION_CABECERA AS AC ON AC.ID_ASIGNACION_CABECERA = AD.ID_ASIGNACION_CABECERA;


UPDATE ASIGNACION_DETALLE set ID_ESTADO = 1
  where ID_ASIGNACION_CABECERA = 103
   (select ID_ASIGNACION_CABECERA
     from ASIGNACION_CABECERA
     where ID_ASIGNACION_CABECERA = 103)
	 
UPDATE ASIGNACION_CABECERA set ID_ESTADO = 1
  where ID_ASIGNACION_CABECERA = 103*/

DROP PROCEDURE IF EXISTS sp_asignacion_eliminar;

CREATE PROCEDURE sp_asignacion_eliminar
	@id_cabecera int
AS
UPDATE ASIGNACION_DETALLE set ID_ESTADO = 0
  where ID_ASIGNACION_CABECERA = @id_cabecera
   (select ID_ASIGNACION_CABECERA
     from ASIGNACION_CABECERA
     where ID_ASIGNACION_CABECERA = @id_cabecera);

UPDATE ASIGNACION_CABECERA set ID_ESTADO = 0
  where ID_ASIGNACION_CABECERA = @id_cabecera;
GO

DROP PROCEDURE IF EXISTS sp_listar_asignaciones_antiguas;

CREATE PROCEDURE sp_listar_asignaciones_antiguas
@idS int
AS
SELECT AC.ID_ASIGNACION_CABECERA AS Código_Asignación,
PET.ID_PETICION AS Código_Petición,
P.CEDULA AS Cedula_Cliente,
CONCAT(P.NOMBRE_1,' ',P.APELLIDO_1) AS Cliente_Nombre,
TA.NOMBRE_TIPO_AMBULANCIA AS Tipo_Ambulancia,
PET.N_AMBULANCIAS AS Cantidad_Ambulancias,
PET.PUNTO_ORIGEN AS Origen, PET.PUNTO_DESTINO AS Destino,
AC.CONDICION as Condición_Asignación, AC.FECHA_REGISTRO
FROM ASIGNACION_CABECERA AC
INNER JOIN PETICION PET ON PET.ID_PETICION = AC.ID_PETICION
INNER JOIN CLIENTE C ON PET.ID_CLIENTE = C.ID_CLIENTE
INNER JOIN PERSONA P ON C.ID_PERSONA = P.ID_PERSONA
INNER JOIN TIPO_AMBULANCIA tA ON TA.ID_TIPO_AMBULANCIA = PET.ID_TIPO_AMBULANCIA
WHERE AC.ID_SECRETARIA = @idS AND AC.ID_ESTADO = 1 AND AC.FECHA_REGISTRO <= Dateadd(YYYY,-3,Getdate());
GO

EXEC sp_listar_asignaciones_antiguas
@idS = 100;